name: autotextformatter
description: Automatically hyphenate or increment numbers on the next line. Simplify and enhance text formatting with this versatile package.
version: 0.0.5
author: Amar Khamkar
homepage: https://github.com/Amark19/autotextformatter

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: